### ISSUE TITLE
New W installation doesn't display pages

### ISSUE THREAD

**Issue by Mement0o** [vincent-peugnet/wcms#281]
I installed W today in a new folder and everything seemed to work fine until I tried to display a page I created: it was empty. Like this:
<img width="335" alt="empty" src="https://user-images.githubusercontent.com/40144264/214371196-243f4f2c-5c12-4a13-915c-76c7fd62d3da.png">

My W version : `v2.3.2-24-g28d4bfb`

I tried both installing with ssh and git clone vs. ftp and I got the same issue.

I just went to the homepage I got an a error message saying: `Error while trying to render files`

This a the JSON of a page I created on this W:

```json
{
    "id": "test",
    "title": "test",
    "description": "",
    "lang": "",
    "tag": [],
    "date": "2023-01-24T14:53:00+0100",
    "datecreation": "2023-01-24T14:53:06+0100",
    "datemodif": "2023-01-24T19:09:50+0100",
    "daterender": "2023-01-24T14:53:06+0100",
    "css": "",
    "javascript": "",
    "body": "test",
    "header": "",
    "main": "",
    "nav": "",
    "aside": "",
    "footer": "",
    "externalcss": [],
    "customhead": "",
    "secure": 0,
    "interface": "body",
    "linkto": [],
    "templatebody": "",
    "templatecss": "",
    "templatejavascript": "",
    "templateoptions": [
        "thumbnail",
        "recursivecss",
        "externalcss",
        "favicon",
        "externaljavascript"
    ],
    "favicon": "",
    "thumbnail": "",
    "authors": [
        "guilhem"
    ],
    "invites": [],
    "readers": [],
    "affcount": 3,
    "visitcount": 0,
    "editcount": 4,
    "editby": [],
    "sleep": 0,
    "redirection": "",
    "refresh": 0,
    "password": null
}
```

This is  the content of `w_error.log`:

```
2023-01-24T14:51:57+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:52:03+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:52:04+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:52:28+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:52:45+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:53:11+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:54:02+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:54:34+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:54:39+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:54:56+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:54:57+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:56:34+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:57:15+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T14:57:15+01:00 [ ERROR ] app/class/Controllerpage.php(99) Could not find Page with the following ID: "2" in /home/guilhem/web/vagues/ensapc/app/class/Modelpage.php(104)
#0 /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php(95): Wcms\Modelpage->get()
#1 /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php(196): Wcms\Controllerpage->recursiverender()
#2 [internal function]: Wcms\Controllerpage->read()
#3 /home/guilhem/web/vagues/ensapc/app/class/Routes.php(102): call_user_func_array()
#4 /home/guilhem/web/vagues/ensapc/index.php(40): Wcms\Routes->match()
#5 {main}
2023-01-24T15:23:39+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T18:34:01+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T18:36:44+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T18:36:45+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T18:36:46+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
2023-01-24T18:39:45+01:00 [ ERROR ] app/class/Modelpage.php(382) Folder does not exist in /home/guilhem/web/vagues/ensapc/app/class/Fs.php(56)
```

And the content of `vagues.club1.fr_error.log`/

```
[Tue Jan 24 14:51:57.639828 2023] [proxy_fcgi:error] [pid 2011219] [client 127.0.0.1:59774] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/_n/edit
[Tue Jan 24 14:52:03.909129 2023] [proxy_fcgi:error] [pid 2011218] [client 127.0.0.1:51576] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/_n/edit
[Tue Jan 24 14:52:04.484862 2023] [proxy_fcgi:error] [pid 2011221] [client 127.0.0.1:51600] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/_n/edit
[Tue Jan 24 14:52:28.422683 2023] [proxy_fcgi:error] [pid 2011290] [client 127.0.0.1:47048] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/_n/edit
[Tue Jan 24 14:52:45.877723 2023] [proxy_fcgi:error] [pid 2011290] [client 127.0.0.1:35444] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/_n/edit
[Tue Jan 24 14:53:11.582839 2023] [proxy_fcgi:error] [pid 2011221] [client 127.0.0.1:38878] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/a.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/a/edit
[Tue Jan 24 14:54:02.757794 2023] [proxy_fcgi:error] [pid 2014023] [client 127.0.0.1:55976] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184'
[Tue Jan 24 14:54:34.908139 2023] [proxy_fcgi:error] [pid 2011219] [client 127.0.0.1:40638] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184'
[Tue Jan 24 14:54:39.640718 2023] [proxy_fcgi:error] [pid 2011220] [client 127.0.0.1:50326] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184'
[Tue Jan 24 14:54:56.634090 2023] [proxy_fcgi:error] [pid 2011220] [client 127.0.0.1:51416] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/_n/edit
[Tue Jan 24 14:54:57.398825 2023] [proxy_fcgi:error] [pid 2011217] [client 127.0.0.1:51422] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/_n/edit
[Tue Jan 24 14:56:34.655689 2023] [proxy_fcgi:error] [pid 2011219] [client 127.0.0.1:57270] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/a.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/
[Tue Jan 24 14:57:15.662663 2023] [proxy_fcgi:error] [pid 2011217] [client 127.0.0.1:52506] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n2.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/
[Tue Jan 24 15:23:39.585845 2023] [proxy_fcgi:error] [pid 2011219] [client 127.0.0.1:57700] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184'
[Tue Jan 24 18:34:01.588199 2023] [proxy_fcgi:error] [pid 2011221] [client 127.0.0.1:46156] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184'
[Tue Jan 24 18:36:44.635720 2023] [proxy_fcgi:error] [pid 2011217] [client 127.0.0.1:37644] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/
[Tue Jan 24 18:36:45.522453 2023] [proxy_fcgi:error] [pid 2011221] [client 127.0.0.1:37646] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/
[Tue Jan 24 18:36:46.125573 2023] [proxy_fcgi:error] [pid 2165382] [client 127.0.0.1:37666] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/ensapc/
[Tue Jan 24 18:39:45.781963 2023] [proxy_fcgi:error] [pid 2011218] [client 127.0.0.1:37288] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/_n.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/ensapc/app/class/Controllerpage.php on line 184'
[Tue Jan 24 18:40:21.166746 2023] [proxy_fcgi:error] [pid 2011217] [client 127.0.0.1:39614] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/test.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/carte/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/carte/test/edit
[Tue Jan 24 18:40:22.398857 2023] [proxy_fcgi:error] [pid 2011221] [client 127.0.0.1:39666] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/test.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/carte/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/carte/test/edit
[Tue Jan 24 18:40:22.671604 2023] [proxy_fcgi:error] [pid 2135959] [client 127.0.0.1:39680] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/test.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/carte/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/carte/test/edit
[Tue Jan 24 18:40:22.897599 2023] [proxy_fcgi:error] [pid 2011218] [client 127.0.0.1:39696] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/test.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/carte/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/carte/test/edit
[Tue Jan 24 18:40:23.056616 2023] [proxy_fcgi:error] [pid 2011217] [client 127.0.0.1:39708] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/test.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/carte/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/carte/test/edit
[Tue Jan 24 18:40:23.248270 2023] [proxy_fcgi:error] [pid 2165382] [client 127.0.0.1:39716] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/test.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/carte/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/carte/test/edit
[Tue Jan 24 18:40:23.433797 2023] [proxy_fcgi:error] [pid 2011219] [client 127.0.0.1:39728] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/test.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/carte/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/carte/test/edit
[Tue Jan 24 18:40:23.647688 2023] [proxy_fcgi:error] [pid 2011220] [client 127.0.0.1:39744] AH01071: Got error 'PHP message: PHP Warning:  file_get_contents(render/test.html): failed to open stream: No such file or directory in /home/guilhem/web/vagues/carte/app/class/Controllerpage.php on line 184', referer: https://vagues.club1.fr/carte/test/edit
```

**Comment by vincent-peugnet** [comment]
Thanks !
I think it is the same as this bug : https://github.com/vincent-peugnet/wcms/issues/270

**Comment by vincent-peugnet** [comment]
Should be fixed, feel free to open it again if not.
